# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f53821a8c9dc90e4664052c9b1abbde7c400d08fb479ef134dbe1ce2a23495c3fdbd5a77a263a4e4484e82f1905498da8e54d4aed8ffc04c10de3c1a60397e4

test:
  secret_key_base: 629739a6a9acad51f094d5f1491b45052e62cf44ea8dfeb50813f8af92fd923ebe21a5f59cb71a652b7198ef2c2e13d73db00e9ce7e712e28547b403abef1797

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
